### ISSUE TITLE
Cant build

### ISSUE THREAD

**Issue by tapthaker** [makhov/fbsimulatorcontrol-example-cli-app#1]
When I try to build the project I get FBSimulatorControl/FBSimulatorControl.h file not found. Attaching the screenshot for the same.
<img width="853" alt="screen shot 2015-11-07 at 1 24 37 pm" src="https://cloud.githubusercontent.com/assets/7520741/11014217/3d1bcee6-8553-11e5-8a58-0acb56dc2632.png">

**Comment by makhov** [comment]
@tapthaker Thanks for feedback.
I updated the source code, please, try again.

**Comment by OSemenovBoyarka** [comment]
@makhov I have exactly the same issue, after cloning the project with current master and Xcode 7.3. 
Do you have any ideas about how to fix that?
